# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ee14719b31f151f1f1fca4e7632958a0c40ca5a5a3fc27041c8ae27c4947e0703b4425e5f10036d0aa37896ec5212a2dca7ad302464d1f732738f696531354

test:
  secret_key_base: c35caabe418ca8755c87abfd25c572a8b6dda8900b9abf1d37a0f2b088b21573b44ef2b2d741ee01b1435d7a91c4e4e339374a504378d88b0cb3cc3ee8a73ea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
